## Numpy - Numerical Python


### Numpy Array
    NumPy is used to work with arrays. The array object in NumPy is called ndarray.

    We can create a NumPy ndarray object by using the array() function.

### Numpy array has two flavours :
    1. Vector    2. Matrix

    vectors are 1-D array and matrix are 2D array.

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
type(my_list)

list

In [3]:
import numpy as np

## Numpy Version

In [4]:
print(np.__version__)

1.21.3


### 0Dimensional Array

## astype

In [49]:
print(np.array(1,2).astype("fl")

TypeError: Cannot interpret '2' as a data type

In [5]:
arr = np.array(12)

In [6]:
print(arr)
print(arr.shape)

12
()


### 1Dimensional Array

In [7]:
a = np.array(my_list)
print(a)
print(a.shape)

[1 2 3]
(3,)


In [8]:
type(a)  

numpy.ndarray

###  MultiDimensional Array

In [9]:
my_mat = [[1,2],[2,3],[3,4],[4,5]]
multi_array = np.array(my_mat)
print(multi_array)
print("\nShape :",multi_array.shape)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]

Shape : (4, 2)


In [10]:
type(multi_array)

numpy.ndarray

In [11]:
  np.array(my_mat)

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

### Check Number of Dimensions
    ndim is used to check the dimension of the array

In [12]:
print(arr);print("\n")
print(a);print("\n")
print(multi_array)

12


[1 2 3]


[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [13]:
print(arr.ndim)
print(a.ndim)
print(multi_array.ndim)

0
1
2


### Higher Dimensional Array
    ndmin=- is used for higher order dimension

In [14]:
higher_array = np.array([1,2,3,4],ndmin=5)

In [15]:
print(higher_array)
print("Dimension :",higher_array.ndim)

[[[[[1 2 3 4]]]]]
Dimension : 5


### Fastest way to create  a array 

#### Using arange() method

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### create a array containing 0

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((5,5))   # multimidensional array of 5 * 5 containing 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((3,5))  # multimidensional array of 3 * 5 containing 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((1))

array([1.])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### linspace

##### The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arrange() function but instead of step it uses sample number. 

In [ ]:
np.linspace

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

###### By default -  numpy.linspace(start, stop, num=50) 

In [28]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [29]:
np.linspace(2.0,3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

### Create an Identity Matrix

In [30]:
np.eye(3)   # identity matrix of 3*# order

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(9)    # identity matrix of 9*9 order.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np.eye(1)

array([[1.]])

### Array using random number

##### np.random.rand()

In [34]:
np.random.rand(2,3)

array([[0.98945232, 0.77769462, 0.04342152],
       [0.10175378, 0.43907956, 0.99250639]])

In [35]:
 np.random.rand(1)

array([0.72258826])

##### np.random.randn()

In [36]:
np.random.randn(2)       # standard distribution

array([-0.60308253,  0.26875191])

In [37]:
np.random.randn(2,5)

array([[-0.1062863 , -1.3391854 , -1.19825179, -2.42209264, -1.18160545],
       [ 1.00226069,  0.84780263, -1.24514128, -0.16467229, -0.6533259 ]])

##### np.random.randint()

In [38]:
np.random.randint(1,100)   # lower value is included and upper value is excluded.

39

In [39]:
np.random.randint(1,100,10) # it will give array of 10 random number between 1 to 100

array([61, 13,  3, 60, 41, 23, 44, 18, 66, 15])

In [40]:
np.random.randint(1,100,10)

array([17, 82, 21, 40, 61, 75, 64, 61, 29, 72])

In [48]:
np.random.randint(1,10,size=(3,3),dtype="int")

array([[4, 1, 7],
       [2, 8, 9],
       [3, 4, 1]])

### Reshape the array

In [41]:
arr = np.arange(25)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(1,100,10)
ranarr

array([31, 12, 83, 86, 16, 73, 59, 52, 97, 78])

In [43]:
arr.reshape(5,5)   # reshaping the array arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.reshape(5,2)    # reshaping the array ranarr

array([[31, 12],
       [83, 86],
       [16, 73],
       [59, 52],
       [97, 78]])

In [45]:
ranarr.reshape(5,3)    

ValueError: cannot reshape array of size 10 into shape (5,3)

In [ ]:
ranarr.max()  # find maximum value in array.

In [ ]:
ranarr.min()   # find minimum value in array.

In [ ]:
ranarr

#### Find Index location of max and min value in array

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.argmin()

#### Find the shape of the array.

In [ ]:
ranarr.shape   

In [ ]:
arr.shape

In [ ]:
a = arr.reshape(5,5)

In [ ]:
a

In [ ]:
a.shape

#### Find the Data type of inside array

In [ ]:
arr.dtype

#### #

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10,3)

### flatten 