## Numpy Indexing and Selection 

In [2]:
import numpy as np

In [6]:
arr = np.arange(0,21,2)

In [7]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Indexing

In [8]:
arr[8]

16

In [9]:
arr[1:5]        #slicing

array([2, 4, 6, 8])

In [10]:
arr[1:5:2]      # slicing with jumping statement

array([2, 6])

In [11]:
arr[::-1]      # Reversing the array

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [12]:
arr[::]        # accessing all element of array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
arr[5:]     # access all elements beyond 5th index

array([10, 12, 14, 16, 18, 20])

#### Change Array Element 

In [16]:
arr[0:5] = 100    # it change the first 5 elemnt of array that is equal to 100.


In [17]:
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

#### Copy an array

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [20]:
arr_copy[:] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

### Indexing and Slicing in 2D array

In [23]:
arr_2d = np.array([[1,2,3],[5,6,7],[10,11,2]])

In [24]:
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 11,  2]])

In [28]:
arr_2d[0][0]     # using double bracket notation

1

In [26]:
arr_2d[0]

array([1, 2, 3])

In [27]:
arr_2d[1][1]

6

In [29]:
# Using single bracket notation 

In [30]:
arr_2d[1,1]

6

In [31]:
arr_2d[0,1]   # syntax : arraay_name[rows,column]

2

In [36]:
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 11,  2]])

In [39]:
arr_2d[:3,2:]   #array_name[rows_slicing,column_slicing]

array([[3],
       [7],
       [2]])

In [42]:
arr_2d[:,:2]   # accessed all rows and their column before index 2.

array([[ 1,  2],
       [ 5,  6],
       [10, 11]])

In [44]:
arr_2d[:,:2:2]    # syntax :-  array_name[row's start:end:step ,column's start:end:step]

array([[ 1],
       [ 5],
       [10]])

###  Accessing array's element with condition

In [45]:
arr = np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
bool_arr = arr > 5

In [49]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [52]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [53]:

arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

### Converting MultiDimensional Array into 1Dimensional

In [1]:
import numpy as np

arr = np.array([[2,4]], ndmin=5)

print(arr)
print('shape of array :', arr.shape)
print(arr.ndim)
a = arr.reshape(-1)
print('shape of array :', arr.reshape(-1))
print(a.ndim)

[[[[[2 4]]]]]
shape of array : (1, 1, 1, 1, 2)
5
shape of array : [2 4]
1


## Seed

In [6]:
a=np.random.randint(1,5,size=(2,4))

In [7]:
a

array([[1, 1, 2, 2],
       [2, 3, 3, 1]])