## Numpy Operation
    . Array with Array   
    . Array with Scalars                                                                                           . Universal Array Functions

In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Array with Array Operation
#### array  with array operation can be performed wih same shape of array
            +            -           *             /            % 

##### Addition

In [4]:
arr + arr  # adition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### Substraction

In [5]:
arr - arr   # Substraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### Multiplication

In [6]:
arr * arr  # multiplication

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

##### Division   ( classic divission)

In [7]:
arr / arr  # Division

/tmp/ipykernel_100018/613687386.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr  # Division


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

##### Floor Division  ( Integer Division)

In [15]:
arr // arr

/tmp/ipykernel_100018/376544773.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr // arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
arr2 = np.arange(5,16)

In [11]:
arr + arr2    #  array  with array operation can be performed wih same shape of array

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [12]:
arr3 = np.arange(0,5)

In [13]:
arr + arr2 + arr3

ValueError: operands could not be broadcast together with shapes (11,) (5,) 

##### Modulus

In [14]:
arr2 % arr   

/tmp/ipykernel_100018/3799020334.py:1: RuntimeWarning: divide by zero encountered in remainder
  arr2 % arr


array([0, 0, 1, 2, 1, 0, 5, 5, 5, 5, 5])

##### Floor Division ( Integer Division)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr3

array([0, 1, 2, 3, 4])

In [18]:
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
arr2 // arr

/tmp/ipykernel_100018/537696743.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr2 // arr


array([0, 6, 3, 2, 2, 2, 1, 1, 1, 1, 1])

##### Classic Division

In [23]:
arr2 / arr

/tmp/ipykernel_100018/2501189345.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr2 / arr


array([       inf, 6.        , 3.5       , 2.66666667, 2.25      ,
       2.        , 1.83333333, 1.71428571, 1.625     , 1.55555556,
       1.5       ])

In [24]:
5 / 0


ZeroDivisionError: division by zero

In [25]:
5 // 0

ZeroDivisionError: integer division or modulo by zero

### Array With Scalers Operation

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr +3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [28]:
arr -1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [29]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [31]:
arr // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [33]:
arr % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1])

## 

In [34]:
a = np.arange(1,10)

In [35]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a / a

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
a //  a

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
a % a

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Universal Array Function

In [4]:
import numpy as np
arr = np.arange(0,11)

#### Square Root

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

#### Exponential

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

#### Maximum

In [7]:
np.max(arr) 

10

#### Minimum

In [8]:
np.min(arr)

0

#### Sort

In [9]:
np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Log

In [10]:
np.log(arr)

/tmp/ipykernel_136091/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])