## Numpy Join 

### Joining of two arrays in Numpy is done using concatination() function.
    This function is used to join two or more arrays of the same shape.
    In case of 2D arrays, this function concatinates two arrays by rows or by columns 
    oining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [2]:
import numpy as np

In [9]:
a = np.arange(11)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
b = np.arange(5,16)

In [8]:
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Concatination
    Synatx : numpy.concatinate((a1,a2,...),axis=0/1)

In [11]:
c = np.concatenate((a,b))

In [13]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15])

In [14]:
d = np.concatenate((a,b),axis=0)

In [15]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15])

In [19]:
e = np.concatenate((a,b),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [3]:
new = np.array([[1,2],[3,4]])
new2 = np.array([[1,2],[4,5]])

In [4]:
print(new);print(".....")
print(new2)

[[1 2]
 [3 4]]
.....
[[1 2]
 [4 5]]


In [5]:
concatination = np.concatenate((new,new2))

In [6]:
concatination

array([[1, 2],
       [3, 4],
       [1, 2],
       [4, 5]])

In [11]:
con = np.concatenate((new,new2),axis=0)

In [12]:
con


array([[1, 2],
       [3, 4],
       [1, 2],
       [4, 5]])

In [13]:
con = np.concatenate((new,new2),axis=1) #Join two 2-D arrays along rows (axis=1):
con

array([[1, 2, 1, 2],
       [3, 4, 4, 5]])

In [34]:
print(new);print(".....")
print(new2)

[[1 2]
 [3 4]]
.....
[[1 2]
 [4 5]]


In [32]:
con = np.concatenate((new,new2),axis=1)

In [33]:
con

array([[1, 2, 1, 2],
       [3, 4, 4, 5]])