### Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,12,14,23,34,455,6,7,89])

In [3]:
arr

array([  1,   2,  12,  14,  23,  34, 455,   6,   7,  89])

In [7]:
np.array_split(arr,5)  # array is splited into 5 part

[array([ 1,  2, 12, 14]), array([ 23,  34, 455]), array([ 6,  7, 89])]

In [8]:
np.array_split(arr ,7)

[array([1, 2]),
 array([12, 14]),
 array([23, 34]),
 array([455]),
 array([6]),
 array([7]),
 array([89])]

In [9]:
np.array_split(arr,4)

[array([ 1,  2, 12]), array([14, 23, 34]), array([455,   6]), array([ 7, 89])]